### ISSUE TITLE
Questions about the SI-SNR

### ISSUE THREAD

**Issue by zhangyi02** [kaituoxu/Conv-TasNet#1]
Thanks for your helpful sharing, but there still some question bothering me.
First, when I run your code, the loss is negative since your loss function is - SNR, but the negative loss seem not common for deep learning.
Then I noticed that, when calculating SNR,  s_target is defined by both the clean and estimated source.  It confused me much, could you give some explanation?

**Comment by songtaoshi** [comment]
hello Kaituo, what is the origin paper of SI-SNR, I have not seen in the paper
