### ISSUE TITLE
Question about  accelerating

### ISSUE THREAD

**Issue by yuanyuan0209** [kaituoxu/Conv-TasNet#11]
It seems that it is low to load dataset, any way to accelate?

您好，感谢您的分享。
但是我发现训练模型的时候，读取数据似乎太慢了，有什么办法能够跑得更快一些吗？
谢谢，祝好！

**Comment by yuanyuan0209** [comment]
It seems that it is low to load dataset, any way to accelate?

您好，感谢您的分享。
但是我发现训练模型的时候，读取数据似乎太慢了，有什么办法能够跑得更快一些吗？
谢谢，祝好！

**Comment by kaituoxu** [comment]
Try large num_workers: https://github.com/kaituoxu/Conv-TasNet/blob/master/src/train.py#L111
