### ISSUE TITLE
Script to make same mixture as WSJ0-2mix and WSJ0- 3mix from any open source dataset e.g., Librispeech

### ISSUE THREAD

**Issue by Satishpas2** [kaituoxu/Conv-TasNet#14]
Hi all!
we dont have access to WSJ dataset.
Could you please guide us how to  make the mixture same as WSJ0-2mix  from any open source dataset like Librispeech or any other open source dataset?

**Comment by jnoelvictorino** [comment]
Hi all,

I am also interested on this one. Currently looking for possible solutions.

**Comment by Satishpas2** [comment]
Hi,
I wrote a python script to make data and list required in create_wav_2speakers.m

You can find the scripts here:
https://github.com/Satishpas2/Speech-Separation

**Comment by kaituoxu** [comment]
Great!
Also, you can see tools/ in this repo.

**Comment by jnoelvictorino** [comment]
Thank you! I will use the link.
