### ISSUE TITLE
Reproduce results - mixing SNR ration

### ISSUE THREAD

**Issue by adiyoss** [kaituoxu/Conv-TasNet#17]
Hi,
Thanks a lot for sharing the code!! 
I'm trying to reproduce your results. I'm running everything exactly as specified, however my best model reaches: SDR: 13.4, SNR-SI: 12.8. 

I was wondering if you changed the mixing SNR ration between the speakers to be in the range of [-5, 5]? or did you leave it to be in the range of [0, 5]?

**Comment by mpariente** [comment]
Just for clarification about the mixing SNR.
The first speaker in mixed with the second speaker with an SNR between 0dB and 5dB. 
This makes that the SNR of a random speaker (out of the two) to the other one is between -5dB and 5dB.
Different papers describe the mixing process with [0, 5] or [-5, 5] but it is actually exactly the same.
