### ISSUE TITLE
RuntimeError: CUDA out of memory. 

### ISSUE THREAD

**Issue by KiAlexander** [kaituoxu/Conv-TasNet#19]
even set batch_size = 3 as default with 3 GPU , I still get the following error, I wanna know how can I solve the problem now?

RuntimeError: CUDA out of memory. Tried to allocate 18.75 MiB (GPU 0; 11.90 GiB total capacity; 9.54 GiB already allocated; 9.00 MiB free; 159.98 MiB cached)

+-------------------------------+----------------------+----------------------+
|   1  TITAN X (Pascal)    Off  | 00000000:02:00.0 Off |                  N/A |
| 25%   44C    P8    11W / 250W |      2MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  TITAN X (Pascal)    Off  | 00000000:03:00.0 Off |                  N/A |
| 23%   39C    P8     9W / 250W |      2MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   3  TITAN X (Pascal)    Off  | 00000000:04:00.0 Off |                  N/A |
| 23%   36C    P8     9W / 250W |      2MiB / 12189MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

**Comment by KiAlexander** [comment]
btw， the sample rate =16000 instead 8000 , is it the reason for the error？

**Comment by mpariente** [comment]
Did you set `id=0,1,2` in the run.sh ?

**Comment by KiAlexander** [comment]
yes,  i idid

**Comment by mpariente** [comment]
Did you experience the same problem with a sample rate of 8k? 
With 16k you'll need twice as much memory.
