### ISSUE TITLE
Reproduce results

### ISSUE THREAD

**Issue by r06944010** [kaituoxu/Conv-TasNet#2]
Hi, can you show your reproduce results of SDR on test set? thanks

**Comment by r06944010** [comment]
Thanks, the result is pretty amazing...

**Comment by hlthu** [comment]
By the way, how long it takes for training on a single GPU?

**Comment by kaituoxu** [comment]
With the best config, batch_size=3 and 1 GeForce GTX 1080 Ti GPU, it will take 100min to train one epoch. So 100 epochs will take about 1 week.
If you have more and better GPU, it will be faster.

**Comment by hlthu** [comment]
Got, Thx

Lu Huang
