### ISSUE TITLE
why are long audio files ignored?

### ISSUE THREAD

**Issue by jjburred** [kaituoxu/Conv-TasNet#20]
https://github.com/kaituoxu/Conv-TasNet/blob/73d42bf3b222d5df1f9538f121280038b0c2da53/src/data.py#L80

hi, thanks for sharing this! 

If I'm not mistaken, in the above code segment it seems that audio files that are longer than one minibatch are ignored for the training. Why? They could be read in segments, otherwise a lot of audio from the database is not used at all.

**Comment by kaituoxu** [comment]
Long files will cause Out-of-memory (OOM) error during training.

You can refine these code if you want : )
