### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by anicolson** [kaituoxu/Conv-TasNet#3]
Hi, I would like to do speech enhancement with your work, do you have a model available? and how do I use your code to enhance speech? 
Thank you!

**Comment by anicolson** [comment]
Do you have access to a cloud service like Dropbox etc.?


It will be clean speech mixed with some background noise.

________________________________

**Comment by kaituoxu** [comment]
If you want to enhance speech, you need to train models by yourself.
I only have models to separate multi-speaker audio.

**Comment by anicolson** [comment]
OK, thank you for your help

________________________________

**Comment by kaituoxu** [comment]
You're welcome :)
