### ISSUE TITLE
Questions about the training and pre-trained model

### ISSUE THREAD

**Issue by xiaoyiming** [kaituoxu/Conv-TasNet#4]
@kaituoxu  Hi , It's really a nice work . Thanks for sharing the code.
However, I have a problem about the training.   How many wave-files you used for training  ?
I use 100000 '.wav' files (about  for training  and batch-size=10 (2GPU ,2080Ti_).It seems each epoch needs about 8 hours. It's too slow. 
And could you please share the pre-trained model? 
I am looking for your replay

**Comment by kaituoxu** [comment]
https://github.com/kaituoxu/Conv-TasNet/issues/2#issuecomment-456738136 provides a speed example, it uses wsj0 dataset which contains 20000 utterances.

I only have wsj0 trained models.

**Comment by xiaoyiming** [comment]
Thanks for replay!  Would you mind share your pre-trained model?  I want to make a comparison with my trained model( on another data set)

**Comment by BlueAnthony** [comment]
Could you share the pre-trained model of wsj0? 
Thank you!

**Comment by kaituoxu** [comment]
@xiaoyiming @BlueAnthony Sorry for the late response.
How can I send the model to you?
I live in China, Email and Baidu Yun is fine :)

**Comment by xiaoyiming** [comment]
@kaituoxu  Thanks  for replay, I live in china too. Email or Baidu cloud is fine. My email  is yiming.xiao@whu.edu.cn and my Baidu cloud  account is  18671211381.

**Comment by BlueAnthony** [comment]
@kaituoxu Thank you very much!!
This is my wyt94yx@gmail.com

**Comment by kaituoxu** [comment]
Hi @xiaoyiming @BlueAnthony 
I share the best pre-trained model and related log on Baidu Yun, you can download by yourself here: https://pan.baidu.com/s/1-Rqm7GwpV7Cc1XzHSpHROg
I also send these files to you by email.
You can find the config in the beginning of train.log.
Thx.

**Comment by xiaoyiming** [comment]
@kaituoxu Thanks for your sharing, I really appreciate it !

**Comment by BlueAnthony** [comment]
@kaituoxu Thanks a lot! God bless you!

**Comment by SashankMLAI** [comment]
@kaituoxu Can you send me as well? Thanks :D 
This is my email address : sasank.kottapalli21@gmail.com

**Comment by kaituoxu** [comment]
Is there any way to upload the trained model on GitHub? So you guys can download model by yourself...

**Comment by SashankMLAI** [comment]
Is it not possible to upload it directly? like he did in the below link?
https://github.com/yu4u/age-gender-estimation

**Comment by SashankMLAI** [comment]
Found a way to download the pretrained model baidu-link provided by @kaituoxu 
Follow the [video](https://www.youtube.com/watch?v=UgSmx26w6TU), for the people outside china. 

> I share the best pre-trained model and related log on Baidu Yun, you can download by yourself here: https://pan.baidu.com/s/1-Rqm7GwpV7Cc1XzHSpHROg

**Comment by kaituoxu** [comment]
@SashankMLAI Thanks for your share!

**Comment by vmagdin** [comment]
@kaituoxu I'm not having much luck downloading the file on my Mac. I think GitHub allows files up to 100MB to be checked into the repository, so you might have luck adding them, at least as separate commits.

**Comment by Satishpas2** [comment]
> Hi @xiaoyiming @BlueAnthony
> I share the best pre-trained model and related log on Baidu Yun, you can download by yourself here: https://pan.baidu.com/s/1-Rqm7GwpV7Cc1XzHSpHROg
> I also send these files to you by email.
> You can find the config in the beginning of train.log.
> Thx.

Can you please send me the pretrained model  mentioned above at:
satish.pas@gmail.com

**Comment by Joepetey** [comment]
I can not download through baidu even following the video, any chance someone can email me the pretrained model:

michaelcastellanos94@yahoo.com

Thank you very much!

**Comment by AlexD123123** [comment]
Hi @kaituoxu!

Great work! 
Is it possible for you to send the model also to my mail? my.111.stuff@gmail.com

Thanks in advance!!

**Comment by adiyoss** [comment]
Hi @kaituoxu!
Nice work! can you send me the model too? My mail is yossiadidrum@gmail.com

Thanks!!

**Comment by Satishpas2** [comment]
Can you please send me the pretrained model mentioned above at:
satish.pas@gmail.com

**Comment by xiaoyiming** [comment]
Hi @kaituoxu ！
    Thanks for sharing the pretrained model. However, the final.pth.tar file downed from your shaped Baidu cloud can not be uncompressed ( it notes that the file is type of the data is unknown or the data is already destroyed) . could you please share the model again?

**Comment by JunzheJosephZhu** [comment]
Check out git large file storage, that allows you to upload the pre-trained models(it's free)

**Comment by Piteryo** [comment]
I managed to download it from Baidu, here it is - https://drive.google.com/open?id=18xCr-N_Ashf9X9q0nxQSVZbDXDk2ONVQ

**Comment by s-kuchuganova** [comment]
> I managed to download it from Baidu, here it is - https://drive.google.com/drive/folders/1P2Bghxm2DGmXOkwRkZXK7NfgSIXjiJ7s?usp=sharing

THANK YOU VERY VERY VERY MUCH!!!

**Comment by boriq** [comment]
Hi! Any chance of re-uploading to drive or sending to borisdv@gmail.com?
