### ISSUE TITLE
error when trying to reduce batch_size less than 64 on DSD100 dataset

### ISSUE THREAD

**Issue by SashankMLAI** [kaituoxu/Conv-TasNet#5]
hey,
First of all, I am very thankful for your amazing work.
I am trying to test the flexibility of the model with [DSD100 ](https://sigsep.github.io/datasets/dsd100.html) dataset. 
Testing to see if the model can separate singer and drums instead of 2-speakers.
I am facing issue while trying to reduce the batch_size to 3.(default = 128)
In solver.py -> _run_one_epoch() -> it is not entering this for loop 
{ for i, (data) in enumerate(data_loader): } when batch_size is less than 64 
else: ram is exceeding 12GB (Titan V) 
Can you please help me understanding this error. What could be the difference in datasets?
Thanks :D

**Comment by SashankMLAI** [comment]
I figured it out thanks. Music file is too huge. Increased the segment length and that worked out. Still facing ram issue, I think I have to split the music files into 30secs clips and try training.
Thanks again for this fabulous implementation @kaituoxu.

**Comment by kaituoxu** [comment]
You're welcome.

Hope you can get good results :)
