### ISSUE TITLE
GPU RAM Issue

### ISSUE THREAD

**Issue by SashankMLAI** [kaituoxu/Conv-TasNet#6]
In cv you have set cv_maxlen = 6 or 8. it doesn't take files above 6 to 8 seconds. When I tried to change that, I faced ram issues. Training has been done but when validation started, i faced out of memory issue. so i cropped the wav files to 4secs and didn't face any issue.

Can you explain me why is that we are facing RAM issue when trying to send more data.
For my project, as i am working on music data, need to increase sample rate. 8000 to 22050. 2.5 times more than your implementation, this needs to split my data into less than 2secs to pass through validation.

Is there no other way to solve this ram issue?   Why is it occupying too much space in ram?
Thanks in advance.

**Comment by SashankMLAI** [comment]
Also, wav files are being separated and giving results for models which I trained myself, but when i used your pretrained model and tried to separate sp1 and sp2, they are separated but the separated files are empty. No sound is produced.

**Comment by kaituoxu** [comment]
1. If your wav file is too long, the Conv-TasNet will be bigger, but GPU memory is limited, of course, so you will face out-of-memory(OOM) issue. To avoid OOM issue, you can try to use CPU to do validation.

2. The pretrained model is trained on wjs0 dataset. If you use it to separate music, of course you will fail.

**Comment by SashankMLAI** [comment]
Thanks for your quick reply.
1. I will try doing what you have suggested, thanks for the suggestion.
     I am just curious to know how gpu ram works in loading the data. till training starts only 1.5 gb is 
     occupied, when 1st epoch starts 6 gb is additionally loaded. and for validation, if i use utterence len = 
     1 batch or 1 segment length, no additional ram is loaded and else-wise my ram is getting full. 
     Can you explain me why 6 gb is being loaded even if my data is less than 1gb?
2. I didn't test your pretrained model on music files, but used files from the link below 
    https://cnl.salk.edu/~tewon/Blind/blind_audio.html I tried with both music and speech data but the 
    separated files s1 and s2 are empty. only if i train myself will i be able to separate?


Thanks.
